### ISSUE TITLE
Yubikey-personalization-gui is not a driver

### ISSUE THREAD

**Issue by fuzzyroddis** [caskroom/homebrew-drivers#121]
#### Description of issue

https://github.com/caskroom/homebrew-cask/issues/31782 migrated yubikey-personalization-gui to caskroom/homebrew-drivers

But it not a driver rather an application that lets you edit settings of your Yubikey.
https://www.yubico.com/support/knowledge-base/categories/articles/yubikey-personalization-tools/

**Comment by commitay** [comment]
>https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
>
> Driver: Software to make a hardware peripheral recognisable and usable by the system. 
> #### If the software is useless without the peripheral, it’s considered a driver.
