### ISSUE TITLE
Cask with dead homepage but functioning url

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-drivers#178]
The [canon-capt-printer-driver](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/canon-capt-printer-driver.rb) Cask has a dead `homepage` but a functioning `url`.

@commitay can you confirm that the `homepage` is dead?

**Comment by commitay** [comment]
Current homepage is dead but we can use this instead, it links to the same `url`.

> http://support-asia.canon-asia.com/contents/ASIA/EN/0100420720.html

**Comment by miccal** [comment]
Thanks!
