### ISSUE TITLE
How to deal with casks that require special system version?

### ISSUE THREAD

**Issue by SteamedFish** [caskroom/homebrew-drivers#349]
nvidia-web-driver's version is related with Kernel build string.

```sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102

$ system_profiler SPSoftwareDataType | grep Version
      System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0
```

if Kernel Build Version and Nvidia web driver version mismatch installation will fail. 

https://gfe.nvidia.com/mac-update has all definition. Here are some of the relations

Kernel Build Version | Required Nvidia Web Driver version
--- | ---
17D2102 | 387.10.10.10.25.159
17D102 | 387.10.10.10.25.158
17D2047 | 387.10.10.10.25.157
17D47 | 387.10.10.10.25.156

**Comment by commitay** [comment]
We don't have method to check anything except a major release. 
i.e. `depends_on macos: '>= :high_sierra'`

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/depends_on.md#depends_on-macos
