### ISSUE TITLE
Extend Documentation

### ISSUE THREAD

**Issue by gramtech** [caskroom/homebrew-drivers#358]
Unless I am missing it I dont see links or details of which drivers are included and what they may do or links to to each of the driver docs etc.

Is this something you are planning on adding?

It seems this repo is realatively popular and could benifit some clarity of all included drivers etc.

:-)

Thanks

**Comment by vitorgalvao** [comment]
That’s not something we’re planning on doing.

I wouldn’t describe this repo as popular in the slightest, and the whole reason these are separated from the main repo is that most drivers have weird names and really specific cases and are hard to name as casks, making the main repo a dump.

You’re expected to know which drivers you need for whatever hardware you have. They all have their corresponding homepage.
