### ISSUE TITLE
Uninstalling canon-imagerunner-printer-driver-ufrii fails when SIP enabled

### ISSUE THREAD

**Issue by sparhomenko** [caskroom/homebrew-drivers#8]
- Steps to reproduce:
  1. `brew cask install canon-imagerunner-printer-driver-ufrii`
  2. Ensure macOS System Integrity Protection (aka rootless mode) is enabled (it is unless you explicitly disabled with by running `csrutil disable` in recovery mode).
  3. `brew cask uninstall canon-imagerunner-printer-driver-ufrii`
- Expected: uninstall completed successfully.
- Actual: uninstall failing with the following:
    ```
    ==> Running uninstall process for canon-imagerunner-printer-driver-ufrii; your password may be necessary
    ==> Removing files from pkgutil Bill-of-Materials
    ==> chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted
    Error: Command failed to execute!

    ==> Failed command:
    /usr/bin/sudo -E -- /bin/chmod -- 777 #<Pathname:/usr/libexec/cups>

    ==> Standard Output of failed command:


    ==> Standard Error of failed command:
    chmod: Unable to change file mode on /usr/libexec/cups: Operation not permitted


    ==> Exit status of failed command:
    #<Process::Status: pid 53602 exit 1>
    ```

With SIP disabled everything works fine, so the workaround is to disable SIP, uninstall, and reenable.  `sudo chmod 777 /usr/libexec/cups` indeed fails with SIP enabled.

A similar problem was reported for [send-to-kindle](https://github.com/caskroom/homebrew-cask/issues/28191) cask, but it was closed as it was decided to delete the cask instead.

It is somewhat strange that install works, but uninstall doesn't - if adjusting `/usr/libexec/cups` permissions is not required to install, why would it be needed to uninstall?

**Comment by vitorgalvao** [comment]
What’s the method Canon recommends to uninstall this software?

**Comment by sparhomenko** [comment]
The HTML documentation from the downloaded .dmg recommends to uninstall the driver by manually removing configured, `/Library/Printers/Canon/CUPS_Printer` and `/Library/Printers/PPDs/Contents/Resources/CNPZU*ZU.ppd.gz`. Not sure which files `uninstall pkgutil: 'jp.co.canon.CUPSPrinter.*'` removes, but it's likely more thorough.

**Comment by vitorgalvao** [comment]
Might just be better to remove the cask, if we can’t support it properly.
