### ISSUE TITLE
Synology software is no driver

### ISSUE THREAD

**Issue by tfeldmann** [caskroom/homebrew-drivers#97]
The Synology software casks in this tap are no drivers and should be moved to homebrew-cask.

- **synology-assistant** Synology Assistant is a desktop utility that searches for Synology DiskStations in the local area network
 - **synology-cloud-station-backup** Cloud Station Backup is a backup service that allows you to back up your files from multiple client computers to a centralized Synology NAS.
- **synology-cloud-station-drive** Cloud Station Drive is an application designed to synchronize files between your Synology NAS and PCs via the Internet (same as Dropbox)
- **synology-photo-station-uploader** Photo Station Uploader is an app for bulk uploading photos and videos to Photo Station
- **synologyeiauthenticator** Evidence Integrity Authenticator is a Windows/Mac application that validates and confirms that the recordings and screenshots made by Synology Surveillance Station

I can see where these are coming from because the software is only usable if you own a synology device. But in contrast to other drivers in this tap the hardware is perfectly usable without these applications. These are standalone-applications very similar to Dropbox etc and no hardware drivers.
Same with **wd-my-cloud**.

**Comment by vitorgalvao** [comment]
Though I understand your point, this is in fact correct. It’s all dependent on how we classify drivers. [I’m submitting an update to the documentation to clarify it](https://github.com/caskroom/homebrew-cask/pull/36513/files).

**Comment by tfeldmann** [comment]
Thanks for the clarification!
By this definition `synologyeiauthenticator` should be moved to homebrew-cask.
> Synology Evidence Integrity Authenticator allows third-party investigators or law enforcement authorities to validate and review videos captured by Synology Surveillance Station.
